version: '3.4'
services:
  api_gerenciador_empresa:
    image: api_gerenciador
    build:
      context: .
      dockerfile: Dockerfile      
    ports:
    - "7020:80"
    depends_on:
    - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Fenix3011
      - ACCEPT_EULA=Y
    volumes:
      - C:\mssql\volumes:/var/opt/mssql/data
    ports:
      - "1450:1433"